version: "3.8"

services:
  livekit-meet:
    image: livekit-meet:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3012:3000"
    configs:
      - source: env_config
        target: /app/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

configs:
  env_config:
    file: ./.env
