# No version attribute needed for Docker Compose v2+

services:
  livekit-meet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3012:3000"
    configs:
      - source: env_config
        target: /app/.env

configs:
  env_config:
    file: ./.env